[workspace]
members = ["CORE", "INTERFACE", "APP_FRONTEND"]
resolver = "2"

[workspace.dependencies]
nalgebra = "0.32"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
